### ISSUE TITLE
解绑重新绑定后, 有时发送会提示还未绑定

### ISSUE THREAD

**Issue by JohnnyWoong** [Vaayne/NotionBoy#24]
![image](https://user-images.githubusercontent.com/5661094/206084805-7e338c29-b4a4-4b68-8430-d6df13494dd8.png)

**Comment by JohnnyWoong** [comment]
> @JohnnyWoong 欢迎反馈，我尽快找时间看看啊

并且发送消息后会丢失重新创建以前条目的标签
![image](https://user-images.githubusercontent.com/5661094/206101342-e4abb90a-7810-46ee-8a33-f7bf13262a5c.png)

**Comment by Vaayne** [comment]
@JohnnyWoong  我发现是我部署里有一个旧的版本，现在应该不会出现一下子有，一下子没有的情况

**Comment by JohnnyWoong** [comment]
> > > @JohnnyWoong 欢迎反馈，我尽快找时间看看啊
> > 
> > 
> > 并且发送消息后会丢失重新创建以前条目的标签 ![image](https://user-images.githubusercontent.com/5661094/206101342-e4abb90a-7810-46ee-8a33-f7bf13262a5c.png)
> 
> 这个有重现的步骤吗？

解绑 - 绑定 发送带标签的消息, 解绑前的数据标签就会被删掉

**Comment by JohnnyWoong** [comment]
> @JohnnyWoong 我发现是我部署里有一个旧的版本，现在应该不会出现一下子有，一下子没有的情况

![image](https://user-images.githubusercontent.com/5661094/206110191-87fd9c19-98ec-4ae3-ad3e-303594762707.png)
现在变这样了..

**Comment by Vaayne** [comment]
> > @JohnnyWoong 我发现是我部署里有一个旧的版本，现在应该不会出现一下子有，一下子没有的情况
> 
> ![image](https://user-images.githubusercontent.com/5661094/206110191-87fd9c19-98ec-4ae3-ad3e-303594762707.png) 现在变这样了..

这个应该就是 token 过期了，需要重新绑定获取一下

**Comment by JohnnyWoong** [comment]
> > > @JohnnyWoong 我发现是我部署里有一个旧的版本，现在应该不会出现一下子有，一下子没有的情况
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/5661094/206110191-87fd9c19-98ec-4ae3-ad3e-303594762707.png) 现在变这样了..
> 
> 这个应该就是 token 过期了，需要重新绑定获取一下

![image](https://user-images.githubusercontent.com/5661094/206111243-999deb05-5e72-4e9e-91d2-3e94f7cf4000.png)
重新绑定后就删标签了

**Comment by Vaayne** [comment]
这个是个 bug 需要修复一下

**Comment by Vaayne** [comment]
fix in https://github.com/Vaayne/NotionBoy/pull/25
