### ISSUE TITLE
保存微信公众号图片提示“未经允许不可引用“

### ISSUE THREAD

**Issue by imbennie** [Vaayne/NotionBoy#46]
保存后，notion查看图片显示如下：
<img width="825" alt="image" src="https://user-images.githubusercontent.com/31159377/217138220-e809a72a-7517-4467-9504-4c2db4af5062.png">

**Comment by Vaayne** [comment]
这是因为微信公众号的图片有防盗链，有两个解决办法
1. 不要使用浏览器，而使用 Notion 客户端打开，可以看到图片，但是图片尺寸可能不对
2. 可联系我，我可以提供付费服务，把这些图片上传到图床，这样就能正常的现实图片

**Comment by Vaayne** [comment]
@imbennie hi，更新了，现在可以正常显示图片，你试试。
